name: Deploy model to endpoint

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Azure run job
      run: |  
        az ml online-deployment create --name diabetes-deployment --endpoint vm-mslearn-mlops-jf10 --resource-group rg-mslearn-mlops --workspace-name mlw-mslear-mlops -f /src/deployment.yml --all-traffic
